on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - name: Install dependencies 
        run: npm install
      - run: npm run electron 
