# Only when pushed to the Masterbranch
on: 
  push:
    branches: ['main']

jobs:
  # Build the Distribution
  build-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Check node.js version
        run: node --version
      - name: Check npm version
        run: npm --version
      - name: Chackout Code
        uses: actions/checkout@v2
      - name: Install dependencies 
        run: npm install
      - run: npm run electron-package-win

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
          name: angulatron
          path: dist/
  # Make the Created Artifact containing the dist downloadable
  deploy:
    runs-on: ubuntu-latest
    needs: build-dist
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Download angulatron
      uses: actions/download-artifact@v2
      with:
        name: angulatron
        path: dist/
